In [1]:
import numpy as np
import pandas as pd
import matplotlib

In [2]:
a=[1,2,3,4,5]
arr1=np.array(a)
print(a)
print(arr1)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [3]:
#numpy로 이차원배열
a=[[1,2,3],[4,5,6]]#미리 이차원 데이터 넣기
arr2=np.array(a)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [4]:
#numpy로 이차원배열
a=[1,2,3,4,5,6]
arr3=np.array(a).reshape(2,3)#일차원 넣은 값을 reshape으로 이차원으로 만들어주기
print(arr3)

[[1 2 3]
 [4 5 6]]


In [5]:
print(type(arr3))
print(arr3.shape)

<class 'numpy.ndarray'>
(2, 3)


In [6]:
arr4=np.arange(1,13).reshape(3,4)
print(arr4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
print(np.sum(arr4))
print(np.mean(arr4))
print(np.sqrt(arr4))
print(np.sum(arr4, axis=0))
print(np.sum(arr4, axis=1))

78
6.5
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]]
[15 18 21 24]
[10 26 42]


In [8]:
b=[3,7,4,9,2,6,8,10,5]
arr5=np.array(b).reshape(3,3)
print(arr5)

[[ 3  7  4]
 [ 9  2  6]
 [ 8 10  5]]


In [9]:
print(np.sort(arr5))#디폴트 : 행기준 정렬
print(np.sort(arr5, axis=0))# 열기준 정렬
print(np.sort(arr5, axis=0)[::-1])#내림차순정렬은 열기준만 가능
print(np.sort(arr5, axis=1))#행기준 정렬

[[ 3  4  7]
 [ 2  6  9]
 [ 5  8 10]]
[[ 3  2  4]
 [ 8  7  5]
 [ 9 10  6]]
[[ 9 10  6]
 [ 8  7  5]
 [ 3  2  4]]
[[ 3  4  7]
 [ 2  6  9]
 [ 5  8 10]]


In [10]:
#pandas로 랜덤배열 생성 
seri=pd.Series(np.random.rand(10))
print(seri)

0    0.078396
1    0.446805
2    0.894034
3    0.648416
4    0.043144
5    0.528140
6    0.739798
7    0.302179
8    0.034664
9    0.445805
dtype: float64


In [11]:
name=['kim','lee','choi','park']
age=[20,30,25,32]
gender=['F','M','M','F']
data={'name':name, 'age':age, 'gender':gender}
df=pd.DataFrame(data)
df

name  age gender
0   kim   20      F
1   lee   30      M
2  choi   25      M
3  park   32      F

In [14]:
#dataFrame에서 값을 검색
df.age

0    20
1    30
2    25
3    32
Name: age, dtype: int64

In [13]:
df['age']

0    20
1    30
2    25
3    32
Name: age, dtype: int64

In [17]:
#없는 필드는 .으로 접근해서 값을 넣을 수 없다
#df.hp=[]
#없는 필드는 반드시 하단 코드처럼 접근해야함
df['hp']=['010-1111-2222','010-2222-3333','010-3333-4444','010-5555-6565']


In [18]:
df.loc[4]=['hong', 35, 'M','010-7777-8888']#loc하면 행추가해줌
df

name  age gender             hp
0   kim   20      F  010-1111-2222
1   lee   30      M  010-2222-3333
2  choi   25      M  010-3333-4444
3  park   32      F  010-5555-6565
4  hong   35      M  010-7777-8888

In [19]:
df.index

Int64Index([0, 1, 2, 3, 4], dtype='int64')

In [20]:
df.columns

Index(['name', 'age', 'gender', 'hp'], dtype='object')

In [21]:
#검색 조건을 통해 검색 
df.loc[[1,4],['name','hp']]

name             hp
1   lee  010-2222-3333
4  hong  010-7777-8888

In [23]:
df.loc[df.gender=='M',['name','gender']]

name gender
1   lee      M
2  choi      M
4  hong      M

In [24]:
df.loc[df.age>=30,['name','age']]

name  age
1   lee   30
3  park   32
4  hong   35

In [26]:
name=['kim','lee','choi','park']
kor=[80,75,90,65]
math=[75, 85,80,65]
data={'name':name, 'kor':kor, 'math':math}
df=pd.DataFrame(data)
df

name  kor  math
0   kim   80    75
1   lee   75    85
2  choi   90    80
3  park   65    65

In [36]:
df

name  kor  math  tot   avg  grade
0   kim   80    75  155  77.5      1
1   lee   75    85  160  80.0      2
2  choi   90    80  170  85.0      1
3  park   65    65  130  65.0      2

In [37]:
df.sort_values(by='kor',ascending=False)

name  kor  math  tot   avg  grade
2  choi   90    80  170  85.0      1
0   kim   80    75  155  77.5      1
1   lee   75    85  160  80.0      2
3  park   65    65  130  65.0      2

In [38]:
df.sort_values(by=['kor','avg'],ascending=False)

name  kor  math  tot   avg  grade
2  choi   90    80  170  85.0      1
0   kim   80    75  155  77.5      1
1   lee   75    85  160  80.0      2
3  park   65    65  130  65.0      2

In [39]:
df.grade.value_counts()

2    2
1    2
Name: grade, dtype: int64

In [35]:
df['grade']=[1,2,1,2]
df.groupby(df.grade).mean()

kor  math    tot    avg
grade                          
1      85.0  77.5  162.5  81.25
2      70.0  75.0  145.0  72.50

In [31]:
df['avg']=(df.kor+df.math)/2
df.median(axis=1)#median 전체 성분의 중간값을 반환

name    kimleechoipark
kor                310
math               305
tot                615
avg              307.5
dtype: object

In [32]:
print(df.kor.corr(df.math))
print(df.kor.corr(df.avg))

0.6094494002200442
0.9174566031726166


In [46]:
#사용자 정의 함수 적용하기 위해서 df에서 숫자가 아닌 열 드롭해줌
df1=df.drop('name', axis=1)
df1

kor  math  tot   avg  grade
0   80    75  155  77.5      1
1   75    85  160  80.0      2
2   90    80  170  85.0      1
3   65    65  130  65.0      2

In [41]:
#사용자 정의 함수
func1=lambda x:x.max()-x.min()

In [43]:
def func2(x):
    return x.max()-x.min()

In [48]:
#열방향으로 함수 적용
print(df1.apply(func1,axis=0))
print(df1.apply(func2,axis=0))

kor      25.0
math     20.0
tot      40.0
avg      20.0
grade     1.0
dtype: float64
kor      25.0
math     20.0
tot      40.0
avg      20.0
grade     1.0
dtype: float64


In [49]:
#행방향으로 함수 적용
print(df1.apply(func1,axis=1))
print(df1.apply(func2,axis=1))

0    154.0
1    158.0
2    169.0
3    128.0
dtype: float64
0    154.0
1    158.0
2    169.0
3    128.0
dtype: float64
